"""empty message

Revision ID: 5c410abf3b1b
Revises: d027cf70a29d
Create Date: 2021-06-05 23:48:51.538973

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c410abf3b1b'
down_revision = 'd027cf70a29d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('show', sa.Column('venue_id', sa.Integer(), nullable=True))
    op.drop_constraint('show_vanue_id_fkey', 'show', type_='foreignkey')
    op.create_foreign_key(None, 'show', 'venue', ['venue_id'], ['id'])
    op.drop_column('show', 'vanue_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('show', sa.Column('vanue_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'show', type_='foreignkey')
    op.create_foreign_key('show_vanue_id_fkey', 'show', 'venue', ['vanue_id'], ['id'])
    op.drop_column('show', 'venue_id')
    # ### end Alembic commands ###
