"""empty message

Revision ID: 931095d6dafe
Revises: 5c410abf3b1b
Create Date: 2021-06-05 23:51:56.908453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '931095d6dafe'
down_revision = '5c410abf3b1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('show', sa.Column('start_time', sa.String(), nullable=True))
    op.drop_column('show', 'start_tame')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('show', sa.Column('start_tame', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('show', 'start_time')
    # ### end Alembic commands ###
