"""empty message

Revision ID: d027cf70a29d
Revises: 247323139c1a
Create Date: 2021-06-05 23:47:01.171001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd027cf70a29d'
down_revision = '247323139c1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('show', sa.Column('vanue_id', sa.Integer(), nullable=True))
    op.add_column('show', sa.Column('artist_id', sa.Integer(), nullable=True))
    op.drop_constraint('show_vanue_fkey', 'show', type_='foreignkey')
    op.drop_constraint('show_artist_fkey', 'show', type_='foreignkey')
    op.create_foreign_key(None, 'show', 'artist', ['artist_id'], ['id'])
    op.create_foreign_key(None, 'show', 'venue', ['vanue_id'], ['id'])
    op.drop_column('show', 'vanue')
    op.drop_column('show', 'artist')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('show', sa.Column('artist', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('show', sa.Column('vanue', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'show', type_='foreignkey')
    op.drop_constraint(None, 'show', type_='foreignkey')
    op.create_foreign_key('show_artist_fkey', 'show', 'artist', ['artist'], ['id'])
    op.create_foreign_key('show_vanue_fkey', 'show', 'venue', ['vanue'], ['id'])
    op.drop_column('show', 'artist_id')
    op.drop_column('show', 'vanue_id')
    # ### end Alembic commands ###
